name: CICD-NESTJS

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/cicd-nest
  VERSION: ${{ github.sha }}
  NAME: cicd


on:
  push:
    branches: ["main"]
    
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout source code
      uses: actions/checkout@v3
    - name: Setup node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.19.0
        cache: 'npm'
    - run: npm install
    - run: npm run test:e2e

  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Set up docker build
      id: buildx
      uses: docker/setup-buildx-actions@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CICD_TEST_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      push: true
      tags: ${{ env.DOCKER_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: [ self-hosted, label-cicd ]
    steps:
      - name: Docker login
        uses: docker/login-actions@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CICD_TEST_TOKEN }}
      - name: Docker run
        run: |
          docker stop ${{ env.NAME }} && docker rm ${{ env.NAME }} && docker rmi ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 80:3000 --name cicd --restart always ${{ env.DOCKER_IMAGE }}:latest